# Generated by Django 5.0 on 2023-12-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialité', models.CharField(default='docteur general', max_length=1000)),
                ('numero_telephone', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('official_facebookpage', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
